### ISSUE TITLE
Setup Travis crons

### ISSUE THREAD

**Issue by machour** [yiisoft/yii-dev-tool#14]
As briefly discussed on slack, it's becoming harder and harder to understand build failures in Yii 3 repos, as packages are inter-dependent and a tiny change in A can brake B without us noticing for days.

As a counter measure, could we setup [Travis cronjobs](https://docs.travis-ci.com/user/cron-jobs/) as suggested by @rob006 on all repositories to run like every 2 days? (still unsure about the right periodicity)

**Comment by rugabarbo** [comment]
Where will we send notifications?

Travis supports the following options:
* [Slack](https://docs.travis-ci.com/user/notifications/#configuring-slack-notifications)
* [Email](https://docs.travis-ci.com/user/notifications/#configuring-email-notifications)
* [webhooks](https://docs.travis-ci.com/user/notifications/#configuring-webhook-notifications)
* [IRC](https://docs.travis-ci.com/user/notifications/#configuring-irc-notifications)
* [Campfire](https://docs.travis-ci.com/user/notifications/#configuring-campfire-notifications)
* [Flowdock](https://docs.travis-ci.com/user/notifications/#configuring-flowdock-notifications)
* [HipChat](https://docs.travis-ci.com/user/notifications/#configuring-hipchat-notifications)
* [Pushover](https://docs.travis-ci.com/user/notifications/#configuring-pushover-notifications)
* [OpsGenie](https://docs.travis-ci.com/user/notifications/#configuring-opsgenie-notifications)

It seems to me that the best idea for group alerts in our case is **Slack**. Travis documentation has [great example](https://docs.travis-ci.com/user/notifications/#configuring-multiple-notification-targets-with-different-configurations) of separating alerts based on the build result. This allows you to receive notifications of successful builds in one channel, and notifications of failed builds in another:

```yml
notifications:
  slack:
    - rooms:
        - <account>:<token>#failures
      on_success: never
      on_failure: always
      template:
        - "%{repository_slug} (%{commit}) : %{message}"
        - "Build details: %{build_url}"
    - rooms:
        - <account>:<token>#successes
      on_success: always
      on_failure: never
      template:
        - "%{repository_slug} (%{commit}) : %{message}"
        - "Build details: %{build_url}"
```

**Comment by samdark** [comment]
Yes, Slack should be fine.

**Comment by rugabarbo** [comment]
@samdark can you add two new slack rooms for these purposes? We will invite everyone who is interested in receiving notifications to these rooms.

**Comment by samdark** [comment]
Added `build-successes` and `build-failures`.

**Comment by rugabarbo** [comment]
@samdark now we need to encrypted credentials for Slack integration, which we can use in public repositories. Set up a [new Travis CI integration](https://docs.travis-ci.com/user/notifications#configuring-slack-notifications) and encrypt the tokens of each room.

I need encrypted credentials for both rooms. Our public configuration will look something like this:
```yml
notifications:
    slack:
        - rooms:
              - secure: "ABC5OwLpwB7L6Ca...."
          on_success: never
          on_failure: always
          template:
              - "%{repository_slug} (%{commit}) : %{message}"
              - "Build details: %{build_url}"
        - rooms:
              - secure: "ABC5OwLpwB7L6Ca...."
          on_success: always
          on_failure: never
          template:
              - "%{repository_slug} (%{commit}) : %{message}"
              - "Build details: %{build_url}"
```

You see here the encrypted string "ABC5OwLpwB7L6Ca....", which I need for adjusting travis configs in yii public repositories.
