### ISSUE TITLE
Version docker-compose

### ISSUE THREAD

**Issue by mapeveri** [yiisoft/yii-dev-tool#74]
I have this problem with docker-compose when I run docker-compose run --rm php bash:

> ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
> For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

The solution for this was change the version in docker-compose like this:

```
version: '3.4'
services:
  php:
    image: yiisoftware/yii-php:7.4-apache
    working_dir: /repo
    volumes:
      - .:/repo
      # For composer usage in container; NOTE! There may be performance issues, see also https://github.com/docker/for-mac/issues/77
      - ~/.composer-docker/cache:/root/.composer/cache:delegated

```
Change version 2.4 to 3.4.

Mi version of docker-compose is:

docker-compose version 1.17.1

Can I send a PR to update?

Thanks!
